# Generated by Django 3.2.2 on 2021-05-06 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('Name', models.CharField(max_length=255)),
                ('Roll_Number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('English', models.IntegerField(default=0)),
                ('Maths', models.IntegerField(default=0)),
                ('Science', models.IntegerField(default=0)),
                ('Optional_subject', models.IntegerField(default=0)),
                ('roll_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.studentdetails')),
            ],
        ),
    ]
